### ISSUE TITLE
Localization issues with German

### ISSUE THREAD

**Issue by nuraeil** [snipe/snipe-it#10242]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We want to use Snipe-IT as a rental and inventory management software in our company but some things are... behaving oddly.

I set the language to German but lots of strings are still in English.

![image](https://user-images.githubusercontent.com/32387849/139223109-df483561-b934-4287-ac95-34a010bf94a6.png)

According to the CrowdIn site, German is fully translated. But when I try to search for certain strings, I am unable to find them.

In debug mode, nothing changed and no errors were output.

![image](https://user-images.githubusercontent.com/32387849/139226767-43beb647-218b-4538-93a7-b381aaa6507b.png)

### Reproduction steps

1. Install current version of Snipe-IT
2. Set localization to German
3. Inspect locations mentioned in the description of the bug and shown in the screenshots

### Expected behavior

All strings should be in German and not in English.

Update Branding Settings -> Aktualisierung des Brandings
Update Localization Settings -> Aktualisierung der Lokalisierung

### Screenshots

![image](https://user-images.githubusercontent.com/32387849/139221650-8955e55d-01bb-4347-b168-b702dd7399d2.png)
![image](https://user-images.githubusercontent.com/32387849/139221706-a028e341-5020-4873-a7ed-69e8847a5e2a.png)
![image](https://user-images.githubusercontent.com/32387849/139221774-6bce7bc0-13c9-45aa-9d63-0dfb8da33891.png)
![image](https://user-images.githubusercontent.com/32387849/139221808-4993b307-6b45-42f5-a0ef-28be56cdfa5b.png)
![image](https://user-images.githubusercontent.com/32387849/139221854-a227650c-72e7-4844-8624-4d6d982f8199.png)

### Snipe-IT Version

v5.3.0 build 6470 (gf87ffb84d)

### Operating System

Ubuntu (Kubernetes environment)

### Web Server

Apache2 proxied through NGINX Ingress

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Google Chrome, Firefox

### Additional context

**Is this a fresh install or an upgrade?**
Semi-fresh install of Snipe-IT as it is a Docker image that has been updated from version to version.

**What OS and web server you're running Snipe-IT on
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)**

Official Docker image runs on a Kubernetes (k8s) cluster, served over a Nginx Ingress.
The installation is fully configured with below config map.
Attached to a MySQL 8.0.24 deployment.

```yaml
  ALLOW_IFRAMING: "false"
  APP_DEBUG: "false"
  APP_ENV: production
  APP_LOCALE: de
  APP_TIMEZONE: Europe/Berlin
  APP_TRUSTED_PROXIES: '*'
  APP_URL: https://[REMOVED]:443
  CORS_ALLOWED_ORIGINS: "null"
  ENABLE_CSP: "false"
  ENABLE_HSTS: "false"
  IMAGE_LIB: gd
  LDAP_MEM_LIM: 2000MB
  LDAP_TIME_LIM: "600"
  LOGIN_LOCKOUT_DURATION: "60"
  LOGIN_MAX_ATTEMPTS: "5"
  MAIL_ENV_ENCRYPTION: tls
  MAIL_ENV_FROM_ADDR: [REMOVED]
  MAIL_ENV_FROM_NAME: '''[REMOVED]'''
  MAIL_ENV_USERNAME: [REMOVED]
  MAIL_PORT_587_TCP_ADDR: [REMOVED]
  MAIL_PORT_587_TCP_PORT: "587"
  MYSQL_DATABASE: snipeit
  MYSQL_PORT_3306_TCP_ADDR: inventory-database
  MYSQL_PORT_3306_TCP_PORT: "3306"
  MYSQL_USER: snipeit
  PRIVATE_FILESYSTEM_DISK: local
  PUBLIC_FILESYSTEM_DISK: local_public
  REFERRER_POLICY: same-origin
```
For the sake of debugging, APP_DEBUG was temporarily set to true.

PHP.ini is also being overriden by a custom one in order to increase the memory limit.

**Indicate whether or not you've manually edited any data directly in the database**
No, no data has been directly manipulated through the MySQL database.
