### ISSUE TITLE
"Error: There was a problem while trying to log you in, please try again." with SAML and Keycloak behind nginx reverse proxy

### ISSUE THREAD

**Issue by kevinveenbirkenbach** [snipe/snipe-it#16186]
This issue is propably related to https://github.com/snipe/snipe-it/issues/14895

**Problem**

When I get redirected back from keycloak to snipe i recieve

![Image](https://github.com/user-attachments/assets/079531b8-12dc-4b5d-88ec-51f3dd1f3020)

My SAML configuration on Snipe is:

![Image](https://github.com/user-attachments/assets/9ec3c1ad-abe0-431a-9d6e-0db5785e88fe)

My Client Configuration on Keycloak is:

![Image](https://github.com/user-attachments/assets/90341c55-1eef-4b41-b9ce-022ef5275692)

![Image](https://github.com/user-attachments/assets/ad431891-505f-4a1a-9c27-b3239ba57442)

It was setup with this ansible role:

https://github.com/kevinveenbirkenbach/cymais/tree/master/roles/docker-snipe_it

using this configuration:
https://github.com/kevinveenbirkenbach/cymais/blob/master/roles/docker-snipe_it/templates/env.j2

producing this nginx configuration:

```
[root@galaxyserver keycloak]# cat /etc/nginx/conf.d/http/servers/inventory.veen.world.conf 
server
{
  server_name inventory.veen.world;

  
      # Include Matomo Tracking Code
    # Deactivate CSP header
add_header Content-Security-Policy: "";

# sub filters to integrate matomo tracking code in nginx websites
sub_filter '</head>' '<script>var _paq = window._paq = window._paq || [];_paq.push(["setDocumentTitle", document.domain + "/" + document.title]);_paq.push(["setCookieDomain", "*.veen.world"]);_paq.push(["setDomains", ["*.veen.world"]]);_paq.push(["enableCrossDomainLinking"]);_paq.push(["trackPageView"]);_paq.push(["trackAllContentImpressions"]);_paq.push(["enableLinkTracking"]);(function() { var u="//matomo.veen.world/"; _paq.push(["setTrackerUrl", u+"matomo.php"]); _paq.push(["setSiteId", "1"]); var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.async=true; g.src=u+"matomo.js"; s.parentNode.insertBefore(g,s);})();</script></head>';
sub_filter '</body>' '<noscript><p><img src="//matomo.veen.world/matomo.php?idsite=1&rec=1" style="border:0;" alt="" /></p></noscript></body>';
sub_filter_once off;  
  
  listen 443 ssl;
listen [::]:443 ssl;
http2 on;
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets on;
ssl_prefer_server_ciphers on;
add_header Strict-Transport-Security max-age=15768000;
ssl_stapling on;
ssl_stapling_verify on;
ssl_certificate /etc/letsencrypt/live/veen.world/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/veen.world/privkey.pem;
ssl_trusted_certificate /etc/letsencrypt/live/veen.world/chain.pem;
  location /
{
  
  proxy_pass http://127.0.0.1:8035/;

  # headers
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Port 443;
  proxy_set_header Accept-Encoding "";

  # WebSocket specific header
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  # deactivate buffering
  proxy_buffering off;
  proxy_request_buffering off;

  # timeouts
  proxy_connect_timeout       1s;
  proxy_send_timeout          900s;
  proxy_read_timeout          900s;
  send_timeout                900s;
}
}
```
and this docker file:
```
services:

# This template needs to be included in docker-compose.yml, which depend on redis
  redis:
    image: redis:alpine
    container_name: snipe_it-redis
    restart: unless-stopped
    logging:
      driver: journald
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - default


# This template needs to be included in docker-compose.yml, which depend on a mariadb database


  application:
    image: snipe/snipe-it:latest
# Base for docker services
    restart: unless-stopped
    env_file:
      - "/opt/docker/snipe_it/.env/env"
    logging:
      driver: journald


    volumes:
      - data:/var/lib/snipeit
    ports:
      - "127.0.0.1:8035:80"
# This template needs to be included in docker-compose.yml containers, which depend on a database, redis and optional additional volumes
    depends_on:
      redis:
        condition: service_healthy

# This template needs to be included in docker-compose.yml containers
    networks:
      central_mariadb:
      default:


# This template needs to be included in docker-compose.yml which contain a database and additional volumes
volumes:

  redis:
  data:

# This template needs to be included in docker-compose.yml
networks:
  central_mariadb:
    external: true
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.102.160/28
```

I appreciate any help :)
