### ISSUE TITLE
Docker container issue

### ISSUE THREAD

**Issue by vgsangiuliano** [snipe/snipe-it#2564]
Dear all,
I am trying to run snipe-it docker container.
I am running CoreOS as OS and docker-compose
CoreOS ip address is 172.20.35.26

My docker-compose.yml is

```
mysql_snipe:
  image: mysql:latest
  container_name: mysql_snipe
  
  environment:
    MYSQL_ROOT_PASSWORD: "mysupersecretpassword"
    MYSQL_DATABASE: "snipe"
    MYSQL_USER: "snipe"
    MYSQL_PASSWORD: "snipesupersecretpassword"
  
  volumes:
    - /home/core/mysql_snipe_data:/var/lib/mysql

phpmyadmin_snipe:
  image: phpmyadmin/phpmyadmin:latest

  container_name: phpmyadmin_snipe
  
  links:
    - mysql_snipe

  ports:
    - "8080:80"
  environment:
    PMA_HOST: "mysql_snipe"

snipe:
  image: snipe/snipe-it:latest

  container_name: snipe
  
  links:
    - mysql_snipe
  
  ports:
    - "8888:80"

  environment:
    APP_ENV: "production"
    APP_DEBUG: "false"
    APP_KEY: "6F9XcfuC16IR3RQxJzFyvhnGKpifM3A6zb5hBbQJbLM="
    APP_URL: "http://172.20.35.26:8888"
    APP_TIMEZONE: "Europe/Rome"
    APP_LOCALE: "en"
    # Mysql Parameters
    MYSQL_ROOT_PASSWORD: "mysupersecretpassword"
    MYSQL_DATABASE: "snipe"
    MYSQL_USER: "snipe"
    MYSQL_PASSWORD: "snipesupersecretpassword"
```
Here is my docker ps output
```
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                           NAMES
a7061576f4e2        snipe/snipe-it:latest          "/entrypoint.sh"         34 minutes ago      Up 34 minutes       443/tcp, 0.0.0.0:8888->80/tcp   snipe
b3a1803e3c62        phpmyadmin/phpmyadmin:latest   "/run.sh phpmyadmin"     34 minutes ago      Up 34 minutes       0.0.0.0:8080->80/tcp            phpmyadmin_snipe
cf7bca2684c0        mysql:latest                   "docker-entrypoint.sh"   34 minutes ago      Up 34 minutes       3306/tcp                        mysql_snipe
```
Apache is running in snipe container
```
sudo docker exec -it snipe /bin/bash
root@a7061576f4e2:/var/www/html# service apache2 status
 * apache2 is running

```
These are apache logs
`
root@a7061576f4e2:/var/log/apache2# tail -100 access.log
172.20.36.34 - - [05/Sep/2016:13:46:22 +0000] "GET / HTTP/1.1" 500 4954 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
172.20.36.34 - - [05/Sep/2016:13:46:22 +0000] "GET / HTTP/1.1" 500 4954 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
172.20.36.34 - - [05/Sep/2016:13:47:30 +0000] "GET / HTTP/1.1" 500 4954 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
172.20.36.34 - - [05/Sep/2016:13:48:52 +0000] "\x16\x03\x01" 400 0 "-" "-"
172.20.36.34 - - [05/Sep/2016:13:48:52 +0000] "\x16\x03\x01" 400 0 "-" "-"
172.20.36.34 - - [05/Sep/2016:13:48:52 +0000] "\x16\x03\x01" 400 0 "-" "-"
172.20.36.34 - - [05/Sep/2016:13:49:05 +0000] "GET / HTTP/1.1" 500 4954 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
root@a7061576f4e2:/var/log/apache2# tail -100 error.log
[Mon Sep 05 13:43:24.180941 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.19 configured -- resuming normal operations
[Mon Sep 05 13:43:24.180990 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D NO_DETACH'
root@a7061576f4e2:/var/log/apache2#
`

When I point my browser to 172.20.35.26:8888 I get
```
Whoops, looks like something went wrong.
```
Could you please help me in understanding where I am wrong?

Thanks
KR
Mirko
