### ISSUE TITLE
" Table 'snipeit.users' doesn't exist" when using docker-compose

### ISSUE THREAD

**Issue by Borkason** [snipe/snipe-it#3581]
#### Expected Behavior

On first run, show http://localhost/setup.php without errors.

-----

#### Actual Behavior

See error:

```
QueryException in Connection.php line 729:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.users' doesn't exist
(SQL: select * from `users` where `id` = 1 and `remember_token` = lGBjg2I7lXkSe9qySnZKNhmOirGAurmqOIluEtQbUHyHjjqesOyn5hBdt4rz and `users`.`deleted_at` is null limit 1)
```
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----

When running Snipe-IT the first time and browsing to http://localhost I see the above mentioned error message.

This is my `docker-compose.yml` and the command to bring it up is ` docker-compose up`.

```
version: "3"

services:

  webapp:
    image: snipe/snipe-it
    ports:
      - "80:80"
    environment:
      - MYSQL_PORT_3306_TCP_ADDR=database
      - MYSQL_ROOT_PASSWORD=my_password1
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my_password1
      - APP_ENV=develop
      - APP_DEBUG=true
      #- APP_ENV=production
      #- APP_DEBUG=false
      - APP_KEY=base64:pHroIaO9f3J9ENqqNmc+M9IK0cW3svnVXv7Jbp34AVo=
      - APP_URL=http://localhost
      - APP_TIMEZONE=Europe/Berlin
      - APP_LOCALE=de
    
  database:
    image: mysql:5.6
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my_password1
      - MYSQL_DATABASE=snipeit
```
