### ISSUE TITLE
Application continually logs user out

### ISSUE THREAD

**Issue by taiidani** [snipe/snipe-it#3624]
#### Expected Behavior (or desired behavior if a feature request)

Logged in users stay logged in for a decent amount of time.

-----

#### Actual Behavior

After a short period (10-60 seconds) of idleness the user is logged out. This also may be triggering regardless of the user being idle or not.

Once logged out it often (but not always) takes 3-4 login attempts before authentication will succeed and allow the user back in.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

Using [the Snipe-IT docker container](https://hub.docker.com/r/snipe/snipe-it/) on Docker Swarm v17.03.0. The application is being an AWS ALB that is terminating SSL for it.

```dockerfile
FROM snipe/snipe-it:v3.6.6

ENV APP_TIMEZONE=US/Pacific \
    APP_LOCALE=en
```

```yml
version: '3.1'

volumes:
  appdata:
    driver: local
    driver_opts:
      type: nfs
      o: <redacted>
      device: ":/snipeit/data"

services:
  app:
    image: company/snipeit
    ports:
      - "10009:80"
    volumes:
      - appdata:/var/lib/snipeit
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
    env_file: ./environment
    environment:
      APP_DEBUG: "true"
      APP_ENV: production
      APP_KEY: <redacted>
      APP_URL: https://<redacted>
      MAIL_ENV_ENCRYPTION: tcp
      MAIL_ENV_FROM_ADDR: <redacted>
      MAIL_ENV_FROM_NAME: <redacted>
      MAIL_ENV_PASSWORD: <redacted>
      MAIL_ENV_USERNAME: <redacted>
      MAIL_PORT_587_TCP_ADDR: <redacted>
      MAIL_PORT_587_TCP_PORT: 587
      MYSQL_DATABASE: snipeit
      MYSQL_PASSWORD: <redacted>
      MYSQL_PORT_3306_TCP_ADDR: <redacted>
      MYSQL_USER: <redacted>
```

No errors are occurring in the browser. Apache is logging the following to stdout:
```
Module ssl disabled.
To activate the new configuration, you need to run:
  service apache2 restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.5.3. Set the 'ServerName' directive globally to suppress this message
```

And the contents of the laravel.log file in the container:
```
[2017-06-02 09:42:18] production.DEBUG: Authenticating user against database.
```

Installation is entirely vanilla -- we ran the initial database migrations and set up an administrator user, then immediately began running into the problems.

The problem has not been reproduceable locally yet.
