### ISSUE TITLE
Docker installation gives SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by back-2-95** [snipe/snipe-it#5340]
#### Expected Behavior (or desired behavior if a feature request)

I did the Docker installation and I get snipe-it on snipe-it.mydomain.tld and I'd expect some screen where I have an empty installation.
-----

#### Actual Behavior

BUT I get this:

`SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = users)`

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Versions and such are the ones coming from docker image.

**Comment by back-2-95** [comment]
And I use docker-compose to get it up:

```
version: "2"

services:

  mysql:
    env_file: ./.env.production
    image: mysql:5.6
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - snipe-it-network

  snipeit:
    env_file: ./.env.production
    image: snipe/snipe-it:v4.2.0
    ports:
      - "80:80"
    volumes:
      - ./data:/var/lib/snipeit
    links:
      - mysql:mysql
    restart: always
    networks:
      - snipe-it-network

volumes:
  data: {}
  database: {}

networks:
  snipe-it-network:
    driver: bridge
```

**Comment by uberbrady** [comment]
Okay, I think I figured out what's going wrong here. To get the link-level environment variables that Snipe-IT needs, you need to use version 1 of the docker-compose file format. As per: https://docs.docker.com/compose/link-env-deprecated/

Docker keeps complaining about the `link` stuff being deprecated, so we're going to have to address this eventually.

I'm poking around with a version-1 `docker-compose.yml` file to see if I can get something working - if so, I can put it into a PR.

**Comment by uberbrady** [comment]
This is what I have so far, but I'm not convinced I have the 'volumes' parameter working how I want. I also think I want to change the names of the containers - 'mysql' is too generic.

```yml
mysql:
  env_file: ./.env.production
  image: mysql:5.6
  volumes:
    - database:/var/lib/mysql
  ports:
    - "3306:3306"
  restart: always

snipeit:
  env_file: ./.env.production
  image: snipe/snipe-it:v4.2.0
  ports:
    - "80:80"
  volumes:
    - data:/var/lib/snipeit
  links:
    - mysql:mysql
  restart: always
```

(Apparently in version 1 of `docker-compose` files, you don't have a version and just specify your services at the root level.)

@back-2-95 can you mess around with this a little and let us know if we're on the right track?
