### ISSUE TITLE
APP_URL not respected by Snipe-IT docker image

### ISSUE THREAD

**Issue by iwittkau** [snipe/snipe-it#6089]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
- I have set `APP_URL` to `https://subdomain.domain.tld:443` but Snipe-IT still generates asset-URLs with the server-IP (e.g. 172.1.1.10:5050).

**To Reproduce**
1. Use given `docker-compose.yml` to bring up the services
2. Configure nginx as reverse proxy

**Expected behavior**
The full webapp is loaded from the given APP_URL

**Server (please complete the following information):**
 - Snipe-IT Version: snipe/snipe-it:v4.6.3 Docker Image
 - OS: Docker on Ubuntu 16.04 LTS
 - Web Server: NGINX reverse-proxy
 - PHP Version: N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.13.06
 - Browser: Firefox
 - Version: 61.0.2 (64-Bit)

**Error Messages**
- There is no direct error message from Snipe-IT but the browser can not load the assets with the URL to a private IP address.

**Additional context**
- official docker image
- set up with mysql in docker-compose
- I use nginx as a reverse proxy and I have it configured with other applications working fine
- I have tried to place the SSL certificate and key in the `ssl` folder, that enabled HTTP but the asset URLs are still wrong
- Snipe-IT says "That URL looks right! Good job!" both on the broken site via the APP_URL and on the raw SERVER-IP:PORT

**docker-compose.yml**

```yml
version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: snipeit
        MYSQL_USER: snipeit
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    env_file:
      - mysql.env
  snipeit:
    image: snipe/snipe-it:v4.6.3
    restart: always
    depends_on:
      - mysql
    volumes:
      - snipeit-data:/var/lib/snipeit
    ports:
      - "5050:80"
      - "5051:443"
    env_file:
      - snipeit.env
volumes:
  snipeit-data:
  mysql-data:
``` 

**snipeit.env**
```bash
# Mysql Parameters
MYSQL_PORT_3306_TCP_ADDR=mysql
MYSQL_PORT_3306_TCP_PORT=3306
MYSQL_DATABASE=snipeit
MYSQL_USER=snipeit
MYSQL_PASSWORD=[REDACTED]

# Email Parameters
# - the hostname/IP address of your mailserver
MAIL_PORT_587_TCP_ADDR=[REDACTED]
#the port for the mailserver (probably 587, could be another)
MAIL_PORT_587_TCP_PORT=465
# the default from address, and from name for emails
MAIL_ENV_FROM_ADDR=[REDACTED]
MAIL_ENV_PASSWORD=[REDACTED]
MAIL_ENV_FROM_NAME=Snipe-IT
# - pick 'tls' for SMTP-over-SSL, 'tcp' for unencrypted
MAIL_ENV_ENCRYPTION=tcp
# SMTP username and password
MAIL_ENV_USERNAME=[REDACTED]

# Snipe-IT Settings
APP_KEY=[REDACTED]
APP_URL=https://[REDACTED]:443
APP_TRUSTED_PROXIES=[REAL-PROXY-IP],[DOCKER-GATEWAY-IP]
APP_ENV=production
APP_DEBUG=false
APP_TIMEZONE=Europe/Berlin
APP_LOCALE=de
```

**nginx.conf**

```conf
# https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/
map $remote_addr $proxy_forwarded_elem {
    # IPv4 addresses can be sent as-is
    ~^[0-9.]+$          "for=$remote_addr";

    # IPv6 addresses need to be bracketed and quoted
    ~^[0-9A-Fa-f:.]+$   "for=\"[$remote_addr]\"";

    # Unix domain socket names cannot be represented in RFC 7239 syntax
    default             "for=unknown";
}

map $http_forwarded $proxy_add_forwarded {
    # If the incoming Forwarded header is syntactically valid, append to it
    "~^(,[ \\t]*)*([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?(;([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?)*([ \\t]*,([ \\t]*([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?(;([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?)*)?)*$" "$http_forwarded, $proxy_forwarded_elem";

    # Otherwise, replace it
    default "$proxy_forwarded_elem";
}

server {
  listen 443;
  server_name subdomain.domain.tld;

  keepalive_timeout 5;

  ssl_certificate     /etc/letsencrypt/live/.../fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/.../privkey.pem;

  location / {
    proxy_set_header Forwarded $proxy_add_forwarded;
    proxy_pass https://[DOCKER-HOST-IP]:5051;
  }

}
```
