### ISSUE TITLE
docker/docker.env variables not expanded to empty strings

### ISSUE THREAD

**Issue by JonathonReinhart** [snipe/snipe-it#6578]
I'm running the `snipe/snipe-it:v4.6.7` Docker image via `docker-compose`. Of course, I modeled my `docker-compose.yml` off of the settings described in https://snipe-it.readme.io/docs/docker.

(I'm actually setting up multiple instances to run against a single DB, due to #3520, and in-part #6501).

The relevant part of `docker-compose.yml`:
```yaml
  assets-corp:
    image: snipe/snipe-it:v4.6.7 
    links:
      - db
    volumes:
      - ./data/snipeit/snipeit_corp:/var/lib/snipeit
    environment:
      VIRTUAL_HOST: assets-corp.example.com

      MYSQL_PORT_3306_TCP_ADDR: db
      #MYSQL_PORT_3306_TCP_PORT: 3306
      MYSQL_DATABASE: snipeit_corp
      MYSQL_USER: snipeit_corp
      MYSQL_PASSWORD: ReDaCtEd

      APP_KEY: base64:ReDaCtEd
```
#### Expected Behavior
I would expect no strange behavior with other environment variables
- I would expect that the default MySQL port (3306) would be used everywhere, as the `MYSQL_PORT_3306_TCP_PORT` environment variable is *not* set.

#### Actual Behavior
It appears that environment variables which are *not set*, but referenced in [`docker/docker.env`](https://github.com/snipe/snipe-it/blob/v4.6.7/docker/docker.env) are kept as literals (and not expanded to empty strings as one would expect).

This has caused (so far) the following bad behaviors:

`${MAIL_ENV_FROM_ADDR}` (literal) shows up in several places:
- On the initial `/setup` page: ![image](https://user-images.githubusercontent.com/1916566/51003300-25d0bc80-1504-11e9-8d80-36c65460e083.png)
- On `/setup/user?` page: ![image](https://user-images.githubusercontent.com/1916566/51003358-63cde080-1504-11e9-95e4-5a0d0de92d2d.png)

`${MYSQL_PORT_3306_TCP_PORT}` shows up on `/admin/backups` after clicking 
![image](https://user-images.githubusercontent.com/1916566/51003612-87455b00-1505-11e9-86e3-482633b90918.png): 

![image](https://user-images.githubusercontent.com/1916566/51003588-71379a80-1505-11e9-8ee2-7f475251e081.png)

- I can work around this by un-commenting `MYSQL_PORT_3306_TCP_PORT` in my `docker-compose.yml` file and setting it to 3306.
