### ISSUE TITLE
APP_TRUSTED_PROXIES on docker image

### ISSUE THREAD

**Issue by hrdkgtm** [snipe/snipe-it#6852]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The only way to modify APP_TRUSTED_PROXIES of snipe-IT on docker is to change the config/trustedproxy.php after the image is running.  

**To Reproduce**
1. Put APP_TRUSTED_PROXIES on your docker env file
2. docker exec -it <container_name> cat .env
3. see that there is actually no APP_TRUSTED_PROXIES mentioned and/or taken from the docker env file

**Expected behavior**
the docker image .env should reflect as much as possible as deployments using other methods. it's just confusing for someone like me who utilize services such as cloudflare SSL, and extensive number of reverse proxies to connect to the snipe-IT. and having to come in the container and change manually everytime is a little bit inefficient and time consuming 

**Screenshots**
```
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
#APP_ENV=develop
#APP_DEBUG=false
#APP_KEY=Change_this_key_or_snipe_will_get_ya
#APP_URL=http://127.0.0.1:32782
#APP_TIMEZONE=US/Pacific
#APP_LOCALE=en


# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=${MYSQL_PORT_3306_TCP_ADDR}
DB_PORT=${MYSQL_PORT_3306_TCP_PORT}
DB_DATABASE=${MYSQL_DATABASE}
DB_USERNAME=${MYSQL_USER}
DB_PASSWORD=${MYSQL_PASSWORD}
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'


# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=${MAIL_PORT_587_TCP_ADDR}
MAIL_PORT=${MAIL_PORT_587_TCP_PORT}
MAIL_USERNAME=${MAIL_ENV_USERNAME}
MAIL_PASSWORD=${MAIL_ENV_PASSWORD}
MAIL_ENCRYPTION=${MAIL_ENV_ENCRYPTION}
MAIL_FROM_ADDR=${MAIL_ENV_FROM_ADDR}
MAIL_FROM_NAME=${MAIL_ENV_FROM_NAME}
MAIL_REPLYTO_ADDR=${MAIL_ENV_FROM_ADDR}
MAIL_REPLYTO_NAME=${MAIL_ENV_FROM_NAME}


# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd


# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false


# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
```

**Server (please complete the following information):**
 - Snipe-IT Docker:v4.6.15 
 - OS: Docker

**Additional context**
- Is this a fresh install or an upgrade? 
  - Fresh
- What OS and web server you're running Snipe-IT on
  - OpenSUSE Kubicmaster, Kubernetes + cri-o
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  - Docker
- Include what you've done so far in the installation, and if you got any error messages along the way.
  - pull the image, configure environment variables for snipe-it and mysql, configure manually inside the container to accept all proxies
- Indicate whether or not you've manually edited any data directly in the database
  - not database, but config files at config/trustedproxy.php

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by cstrock** [comment]
This issue is still occurring.
If you pass APP_TRUSTED_PROXIES= x.x.x.x (via .env file) then it doesn't end up in the trustedproxy.php file.

**Comment by acidicX** [comment]
I have the same issue. Is there any workaround for the time being?
I've tried to edit the files in the container directly but with no success.

**Comment by acidicX** [comment]
@snipe I'd be happy to contribute but I am missing how the Docker env is piped through to the webapp, can you maybe point me to the right files to debug this further?

**Comment by hrdkgtm** [comment]
Hey its been a while since i didn't check on this. I'm also down to check things further when I have time.
 but I am not sure if this issue still occurs with the v4.7.5 of snipe-it. anyone tested it yet?

**Comment by acidicX** [comment]
I've got it working now.

My nginx config:

```nginx
# Snipe-IT Docker Daemon
upstream snipe-it-docker {
        server 127.0.0.1:5544 max_fails=0;
}

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        # change hostname and certs
        server_name snipeit.myhost.tld;
        ssl_certificate /path/to/certs/fullchain.pem;
        ssl_certificate_key /path/to/certs/privkey.pem;

        if ($scheme != "https") {
                return 301 https://$host$request_uri;
        }

        location / {
                proxy_http_version 1.1;
                client_max_body_size 100M;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Frame-Options SAMEORIGIN;
                proxy_buffers 256 16k;
                proxy_buffer_size 16k;
                proxy_read_timeout 600s;
                proxy_pass http://snipe-it-docker;
        }
}
```

The docker-compose:

```yaml
version: '3'

services:

  app:
    image: snipe/snipe-it
    restart: unless-stopped
    env_file: snipeit.env
    ports:
      - 127.0.0.1:5544:80
    environment:
      - APP_KEY=your_key
      - APP_URL=https://snipeit.host.tld
      - APP_TRUSTED_PROXIES="192.168.0.0/24,10.0.0.0/24,127.0.0.1"
      - MAIL_FROM_ADDR=your@mail.tld
      - MAIL_REPLYTO_ADDR=your@mail.tld
    depends_on:
      - db
      - mail
    volumes:
      - ./volumes/snipeit:/var/lib/snipeit

  db:
    image: mariadb/server
    restart: unless-stopped
    env_file: snipeit.env
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  mail:
    image: catatnight/postfix
    restart: unless-stopped
    environment:
      - maildomain=peerigon.com
      - smtp_user=postfix:postfix
```

## The only remaining problem

Even though my nginx does TLS and my clients come in with https, snipe-it puts out http URLs which will not work obviously. Is there a setting to force https scheme in snipe-it?
